apiVersion: v1
kind: Pod
metadata:
   name: mypod-node-sel
   labels:
      app: myapp
spec:
   containers:
   - name: appcon
     image: nginx:latest
     ports:
     - containerPort: 80
   - name: con2
     image: tomcat:latest
     ports:
     - containerPort: 8080
   nodeSelector:
      cpu: intel


