apiVersion: v1
kind: Pod
metadata:
   name: mypod-live-tcp
   labels:
      app: myapp
   annotations:
      description: "this is sample pod"
spec:
   containers:
   - name: appcon
     image: nginx:latest
     ports:
     - containerPort: 80
     livenessProbe:
        tcpSocket:
           port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
     readinessProbe:
        tcpSocket:
           port: 80
        initialDelaySeconds: 10
        periodSeconds: 5


